# syntax=docker/dockerfile:1

FROM	debian:bookworm-slim

RUN		apt-get update && apt-get install -y \
		php-fpm php-mysql curl \
		&& rm -rf /var/lib/apt/lists/*

COPY	tools/wp_script.sh /etc/wordpress/wp_script.sh

RUN		chmod +x /etc/wordpress/wp_script.sh

EXPOSE	9000

ENTRYPOINT ["/etc/wordpress/wp_script.sh"]