# syntax=docker/dockerfile:1

FROM	debian:bookworm-slim

RUN		apt-get update && apt-get install -y nginx openssl

COPY	requirements/nginx/conf/nginx.conf /etc/nginx/nginx.conf
COPY	requirements/nginx/tools/nginx_script.sh /etc/nginx/nginx_script.sh

COPY	secrets/nginx.key /etc/ssl/private/nginx.key
COPY	secrets/nginx.crt /etc/ssl/certs/nginx.crt

RUN		chmod +x /etc/nginx/nginx_script.sh

EXPOSE	443

ENTRYPOINT ["/etc/nginx/nginx_script.sh"]