# syntax=docker/dockerfile:1

FROM	debian:bookworm-slim

RUN		apt-get update && apt-get install -y nginx openssl

COPY	conf/nginx.conf /etc/nginx/nginx.conf
COPY	tools/nginx_script.sh /etc/nginx/nginx_script.sh

RUN		chmod +x /etc/nginx/nginx_script.sh

EXPOSE	443

ENTRYPOINT ["/etc/nginx/nginx_script.sh"]