CREATE DATABASE IF NOT EXISTS __MYSQL_DATABASE__;
CREATE USER IF NOT EXISTS '__MYSQL_USER__'@'%' IDENTIFIED BY '__MYSQL_PASSWORD__';
GRANT ALL PRIVILEGES ON __MYSQL_DATABASE__.* TO '__MYSQL_USER__'@'%';
ALTER USER 'root'@'localhost' IDENTIFIED BY '__MYSQL_ROOT_PASSWORD__';
-- ALTER USER 'root'@'localhost'
-- IDENTIFIED VIA mysql_native_password
-- USING PASSWORD('__MYSQL_ROOT_PASSWORD__');
-- use this if i get login issues
FLUSH PRIVILEGES;